"use client";

import { useActionState, useEffect, useState } from "react";
import { X } from "lucide-react";

type Customer = {
  id: string; code: string; name: string; contact: string; phone: string; link_slug: string; active: boolean;
  orders?: { id: string; order_no: string; manual_total: number | null; discount: number; order_items: { qty: number; price: number }[] }[];
  payments?: { id: string; order_id: string | null; amount: number; method: string; note: string; created_at: string }[];
};
type Action = (formData: FormData) => void | Promise<void>;
type PaymentState = { ok: boolean; message: string } | null;
type CustomerAction = (formData: FormData) => void | Promise<void>;

function CustomerForm({ customer, action, onClose }: { customer: Customer | null; action: CustomerAction; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: PaymentState, formData: FormData): Promise<PaymentState> => {
    try { await action(formData); return { ok: true, message: "Cari kaydedildi." }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Cari kaydedilemedi." }; }
  }, null);
  useEffect(() => { if (state?.ok) window.setTimeout(onClose, 650); }, [state, onClose]);
  return <form action={formAction} className="payment-modal-form">{customer && <input type="hidden" name="id" value={customer.id} />}<div className="field"><label className="lbl">Kod</label><input className="input" name="code" defaultValue={customer?.code ?? ""} required /></div><div className="field"><label className="lbl">Firma adı</label><input className="input" name="name" defaultValue={customer?.name ?? ""} required /></div><div className="field"><label className="lbl">Yetkili</label><input className="input" name="contact" defaultValue={customer?.contact ?? ""} /></div><div className="field"><label className="lbl">Telefon</label><input className="input" name="phone" defaultValue={customer?.phone ?? ""} /></div>{state && <p className={state.ok ? "form-success" : "form-error"}>{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Kaydediliyor…" : "Kaydet"}</button></div></form>;
}

function PaymentForm({ customer, action, onClose }: { customer: Customer; action: Action; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: PaymentState, formData: FormData): Promise<PaymentState> => {
    try { await action(formData); return { ok: true, message: "Tahsilat kaydedildi." }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Tahsilat kaydedilemedi." }; }
  }, null);
  useEffect(() => { if (state?.ok) window.setTimeout(onClose, 650); }, [state, onClose]);
  return <form action={formAction} className="payment-modal-form"><input type="hidden" name="customer_id" value={customer.id} /><div className="field"><label className="lbl">Sipariş (isteğe bağlı)</label><select className="input" name="order_id" defaultValue=""><option value="">Cari hesaba işle</option>{customer.orders?.map((order) => <option key={order.id} value={order.id}>{order.order_no}</option>)}</select></div><div className="field"><label className="lbl">Tutar</label><input className="input" name="amount" type="number" min="0.01" step="0.01" required autoFocus /></div><div className="field"><label className="lbl">Yöntem</label><select className="input" name="method"><option>Nakit</option><option>Havale</option><option>Kredi Kartı</option></select></div><div className="field"><label className="lbl">Not</label><input className="input" name="note" placeholder="Ödeme açıklaması…" /></div>{state && <p className={state.ok ? "form-success" : "form-error"}>{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Kaydediliyor…" : "Tahsilatı Kaydet"}</button></div></form>;
}

function DeletePaymentForm({ payment, action, onClose }: { payment: { id: string; amount: number }; action: Action; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: PaymentState, formData: FormData): Promise<PaymentState> => {
    try { await action(formData); onClose(); return { ok: true, message: "Tahsilat silindi." }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Tahsilat silinemedi." }; }
  }, null);
  return <form action={formAction} className="delete-payment-form"><input type="hidden" name="id" value={payment.id} /><div className="danger-callout"><b>Tehlikeli işlem</b><span>Bu tahsilat kaydı kalıcı olarak silinecek.</span></div><div className="field"><label className="lbl" htmlFor="delete-payment-password">Mevcut şifreniz</label><input className="input" id="delete-payment-password" name="current_password" type="password" autoComplete="current-password" required autoFocus /></div>{state && !state.ok && <p className="form-error">{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-danger" type="submit" disabled={pending}>{pending ? "Siliniyor…" : "Kalıcı olarak sil"}</button></div></form>;
}

export default function CustomerLinks({ customers, paymentAction, createAction, updateAction, deletePaymentAction, updatePaymentAction }: { customers: Customer[]; paymentAction: Action; createAction: CustomerAction; updateAction: CustomerAction; deletePaymentAction: Action; updatePaymentAction: Action }) {
  const [copied, setCopied] = useState<string | null>(null);
  const [origin, setOrigin] = useState("");
  const [paymentCustomer, setPaymentCustomer] = useState<Customer | null>(null);
  const [deletePaymentTarget, setDeletePaymentTarget] = useState<{ id: string; amount: number } | null>(null);
  const [customerForm, setCustomerForm] = useState<Customer | null | undefined>(undefined);
  useEffect(() => setOrigin(window.location.origin), []);
  function getLink(slug: string) { return `${origin}/siparis/${slug}`; }
  async function copyLink(slug: string) { await navigator.clipboard.writeText(getLink(slug)); setCopied(slug); window.setTimeout(() => setCopied(null), 1800); }
  return <><div className="customer-toolbar"><button className="btn btn-primary" type="button" onClick={() => setCustomerForm(null)}>+ Yeni Cari</button></div><div className="tbl-wrap"><table className="tbl"><thead><tr><th>Kod</th><th>Firma</th><th>Satış</th><th>Tahsilat</th><th>Bakiye</th><th>Link</th><th></th></tr></thead><tbody>{customers.map((customer) => {
    const sales = (customer.orders ?? []).reduce((sum, order) => sum + (order.manual_total ?? order.order_items.reduce((total, item) => total + Number(item.qty) * Number(item.price), 0) - Number(order.discount ?? 0)), 0);
    const paid = (customer.payments ?? []).reduce((sum, payment) => sum + Number(payment.amount), 0);
    return <tr key={customer.id}><td className="mono">{customer.code}</td><td><b>{customer.name}</b><div className="sub">{customer.contact || "Yetkili belirtilmemiş"}</div></td><td className="num">₺{sales.toFixed(2)}</td><td className="num">₺{paid.toFixed(2)}</td><td className={`num ${sales - paid > 0 ? "danger-text" : ""}`}><b>₺{(sales - paid).toFixed(2)}</b></td><td><div className="customer-link-actions"><button className="btn btn-ghost btn-sm" type="button" onClick={() => copyLink(customer.link_slug)}>{copied === customer.link_slug ? "Kopyalandı ✓" : "Linki Kopyala"}</button><a className="btn btn-primary btn-sm" href={`https://wa.me/?text=${encodeURIComponent(`${customer.name} sipariş linkiniz: ${getLink(customer.link_slug)}`)}`} target="_blank" rel="noreferrer">WhatsApp</a><button className="btn btn-ghost btn-sm" type="button" onClick={() => setPaymentCustomer(customer)}>Tahsilat</button></div></td><td><button className="btn btn-ghost btn-sm" type="button" onClick={() => setCustomerForm(customer)}>Düzenle</button></td></tr>;
  })}</tbody></table></div>{customerForm !== undefined && <div className="modal-bg open"><div className="modal payment-modal"><div className="modal-head"><div><div className="crumb">Cari hesap</div><h3>{customerForm ? "Cariyi düzenle" : "Yeni cari"}</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => setCustomerForm(undefined)}><X className="ic" /></button></div><CustomerForm customer={customerForm} action={customerForm ? updateAction : createAction} onClose={() => setCustomerForm(undefined)} /></div></div>}{paymentCustomer && <div className="modal-bg open"><div className="modal payment-modal"><div className="modal-head"><div><div className="crumb">Cari tahsilat</div><h3>{paymentCustomer.name}</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => setPaymentCustomer(null)}><X className="ic" /></button></div><section><h4>Tahsilat Geçmişi</h4>{paymentCustomer.payments?.length ? <div className="payment-history">{paymentCustomer.payments.map((payment) => <div className="payment-history-row" key={payment.id}><div><b>₺{Number(payment.amount).toFixed(2)}</b><span>{payment.method}</span></div><div className="sub">{new Date(payment.created_at).toLocaleDateString("tr-TR")}{payment.note && <><br />{payment.note}</>}</div><details className="payment-edit"><summary className="btn btn-ghost btn-sm">Düzenle</summary><form action={updatePaymentAction}><input type="hidden" name="id" value={payment.id} /><input className="input" name="amount" type="number" min="0.01" step="0.01" defaultValue={payment.amount} /><select className="input" name="method" defaultValue={payment.method}><option>Nakit</option><option>Havale</option><option>Kredi Kartı</option></select><input className="input" name="note" defaultValue={payment.note} placeholder="Not" /><button className="btn btn-primary btn-sm" type="submit">Kaydet</button></form></details><button className="btn btn-danger btn-sm" type="button" onClick={() => setDeletePaymentTarget({ id: payment.id, amount: Number(payment.amount) })}>Sil</button></div>)}</div> : <div className="empty">Henüz tahsilat kaydı yok.</div>}</section><div className="payment-divider" /><section><h4>Yeni Tahsilat Ekle</h4><PaymentForm customer={paymentCustomer} action={paymentAction} onClose={() => setPaymentCustomer(null)} /></section></div></div>}{deletePaymentTarget && <div className="modal-bg open"><div className="modal payment-modal"><div className="modal-head"><div><div className="crumb">Tahsilat silme</div><h3>Silme işlemini onayla</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => setDeletePaymentTarget(null)}><X className="ic" /></button></div><DeletePaymentForm payment={deletePaymentTarget} action={deletePaymentAction} onClose={() => { setDeletePaymentTarget(null); setPaymentCustomer(null); }} /></div></div>}</>;
}
