"use client";

import { useActionState, useEffect, useState } from "react";
import { MoreHorizontal, X } from "lucide-react";

type Customer = {
  id: string; code: string; name: string; contact: string; phone: string; link_slug: string; active: boolean;
  orders?: { id: string; order_no: string; manual_total: number | null; discount: number; order_items: { qty: number; price: number }[] }[];
  payments?: { id: string; order_id: string | null; amount: number; method: string; note: string; status?: string; created_at: string }[];
};
type Action = (formData: FormData) => void | Promise<void>;
type PaymentState = { ok: boolean; message: string } | null;
type CustomerAction = (formData: FormData) => void | Promise<void>;

function slugify(value: string) {
  return value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/ı/g, "i").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function CustomerForm({ customer, action, onClose }: { customer: Customer | null; action: CustomerAction; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: PaymentState, formData: FormData): Promise<PaymentState> => {
    try { await action(formData); return { ok: true, message: "Cari kaydedildi." }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Cari kaydedilemedi." }; }
  }, null);
  const [name, setName] = useState(customer?.name ?? "");
  const [slug, setSlug] = useState(customer?.link_slug ?? "");
  const [slugEdited, setSlugEdited] = useState(false);
  useEffect(() => { if (state?.ok) window.setTimeout(onClose, 650); }, [state, onClose]);
  function onNameChange(value: string) { setName(value); if (!slugEdited) setSlug(slugify(value)); }
  function onSlugChange(value: string) { setSlugEdited(true); setSlug(slugify(value)); }
  const origin = (process.env.NEXT_PUBLIC_SITE_URL || (typeof window !== "undefined" ? window.location.origin : "")).replace(/\/$/, "");
  return <form action={formAction} className="payment-modal-form">{customer && <input type="hidden" name="id" value={customer.id} />}<div className="field"><label className="lbl">Kod</label><input className="input" name="code" defaultValue={customer?.code ?? ""} required /></div><div className="field"><label className="lbl">Firma adı</label><input className="input" name="name" value={name} onChange={(event) => onNameChange(event.target.value)} required /></div><div className="field"><label className="lbl">Yetkili</label><input className="input" name="contact" defaultValue={customer?.contact ?? ""} /></div><div className="field"><label className="lbl">Telefon</label><input className="input" name="phone" defaultValue={customer?.phone ?? ""} /></div><div className="field"><label className="lbl">Sipariş linki adresi (slug)</label><input className="input" name="link_slug" value={slug} onChange={(event) => onSlugChange(event.target.value)} placeholder="firma-adi" /><span className="sub">Firma adından otomatik dolar; istersen elle değiştirebilirsin. Link: {origin}/siparis/<b>{slug || "firma-adi"}</b>{customer && slug !== customer.link_slug ? " · Not: değiştirirsen eski link çalışmaz." : ""}</span></div>{state && <p className={state.ok ? "form-success" : "form-error"}>{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Kaydediliyor…" : "Kaydet"}</button></div></form>;
}

function PaymentForm({ customer, action, onClose }: { customer: Customer; action: Action; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: PaymentState, formData: FormData): Promise<PaymentState> => {
    try { await action(formData); return { ok: true, message: "Tahsilat kaydedildi." }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Tahsilat kaydedilemedi." }; }
  }, null);
  useEffect(() => { if (state?.ok) window.setTimeout(onClose, 650); }, [state, onClose]);
  return <form action={formAction} className="payment-modal-form"><input type="hidden" name="customer_id" value={customer.id} /><div className="field payment-amount-field"><label className="lbl">Tutar</label><div className="payment-amount-input"><span>₺</span><input className="input" name="amount" type="number" inputMode="decimal" min="0.01" step="0.01" placeholder="0,00" required autoFocus /></div></div><div className="field"><label className="lbl">Sipariş <span className="optional-label">İsteğe bağlı</span></label><select className="input" name="order_id" defaultValue=""><option value="">Cari hesaba işle</option>{customer.orders?.map((order) => <option key={order.id} value={order.id}>{order.order_no}</option>)}</select></div><div className="field"><label className="lbl">Yöntem</label><select className="input" name="method"><option>Nakit</option><option>Havale</option><option>Kredi Kartı</option></select></div><details className="payment-note-details"><summary>+ Not ekle</summary><div className="field"><label className="lbl">Not</label><input className="input" name="note" placeholder="Ödeme açıklaması…" /></div></details>{state && <p className={state.ok ? "form-success" : "form-error"}>{state.message}</p>}<div className="modal-actions payment-modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Kaydediliyor…" : "Tahsilatı Kaydet"}</button></div></form>;
}

function DeletePaymentForm({ payment, action, onClose }: { payment: { id: string; amount: number }; action: Action; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: PaymentState, formData: FormData): Promise<PaymentState> => {
    try { await action(formData); onClose(); return { ok: true, message: "Tahsilat iptal edildi." }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Tahsilat iptal edilemedi." }; }
  }, null);
  return <form action={formAction} className="delete-payment-form"><input type="hidden" name="id" value={payment.id} /><div className="danger-callout"><b>Tahsilatı iptal et</b><span>Bu tahsilat geçmişte korunacak, bakiyeden düşülecek ve iptal olarak işaretlenecek.</span></div><div className="field"><label className="lbl" htmlFor="delete-payment-password">Mevcut şifreniz</label><input className="input" id="delete-payment-password" name="current_password" type="password" autoComplete="current-password" required autoFocus /></div>{state && !state.ok && <p className="form-error">{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-danger" type="submit" disabled={pending}>{pending ? "İptal ediliyor…" : "İptal et"}</button></div></form>;
}

function DeleteCustomerForm({ customer, action, onClose }: { customer: Customer; action: CustomerAction; onClose: () => void }) {
  const hasHistory = (customer.orders?.length ?? 0) > 0 || (customer.payments?.length ?? 0) > 0;
  const [state, formAction, pending] = useActionState(async (_previous: PaymentState, formData: FormData): Promise<PaymentState> => {
    try { await action(formData); onClose(); return { ok: true, message: "" }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Cari silinemedi." }; }
  }, null);
  return <form action={formAction} className="delete-payment-form"><input type="hidden" name="id" value={customer.id} /><div className="danger-callout"><b>{customer.name}</b><span>{hasHistory ? "Bu carinin sipariş/tahsilat geçmişi var. Kalıcı silinemez; bunun yerine PASİFE alınır (linki çalışmaz, geçmiş korunur). İstediğinde tekrar aktifleştirebilirsin." : "Bu cari kalıcı olarak silinecek. Bu işlem geri alınamaz."}</span></div><div className="field"><label className="lbl" htmlFor="delete-customer-password">Mevcut şifreniz</label><input className="input" id="delete-customer-password" name="current_password" type="password" autoComplete="current-password" required autoFocus /></div>{state && !state.ok && <p className="form-error">{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-danger" type="submit" disabled={pending}>{pending ? "İşleniyor…" : hasHistory ? "Pasife al" : "Kalıcı olarak sil"}</button></div></form>;
}

export default function CustomerLinks({ customers, paymentAction, createAction, updateAction, deletePaymentAction, updatePaymentAction, deleteCustomerAction, reactivateAction }: { customers: Customer[]; paymentAction: Action; createAction: CustomerAction; updateAction: CustomerAction; deletePaymentAction: Action; updatePaymentAction: Action; deleteCustomerAction: CustomerAction; reactivateAction: Action }) {
  const [copied, setCopied] = useState<string | null>(null);
  const [origin, setOrigin] = useState((process.env.NEXT_PUBLIC_SITE_URL || "").replace(/\/$/, ""));
  const [paymentCustomer, setPaymentCustomer] = useState<Customer | null>(null);
  const [editingPaymentId, setEditingPaymentId] = useState<string | null>(null);
  const [deletePaymentTarget, setDeletePaymentTarget] = useState<{ id: string; amount: number } | null>(null);
  const [deleteCustomerTarget, setDeleteCustomerTarget] = useState<Customer | null>(null);
  const [customerForm, setCustomerForm] = useState<Customer | null | undefined>(undefined);
  useEffect(() => { if (!process.env.NEXT_PUBLIC_SITE_URL) setOrigin(window.location.origin); }, []);
  useEffect(() => { if (editingPaymentId) document.querySelectorAll(".payment-row-menu[open]").forEach((menu) => menu.removeAttribute("open")); }, [editingPaymentId]);
  function getLink(slug: string) { return `${origin}/siparis/${slug}`; }
  async function copyLink(slug: string) { await navigator.clipboard.writeText(getLink(slug)); setCopied(slug); window.setTimeout(() => setCopied(null), 1800); }
  return <><div className="section-head customer-page-head"><div><div className="crumb">Operasyon</div><h2>Cari & Tahsilat</h2></div><div className="spacer" /><button className="btn btn-primary" type="button" onClick={() => setCustomerForm(null)}>+ Yeni Cari</button></div><div className="card card-pad customer-list-card"><div className="tbl-wrap customer-table-wrap"><table className="tbl"><thead><tr><th>Kod</th><th>Firma</th><th>Satış</th><th>Tahsilat</th><th>Bakiye</th><th>Link</th><th></th></tr></thead><tbody>{customers.map((customer) => {
    const sales = (customer.orders ?? []).reduce((sum, order) => sum + (order.manual_total ?? order.order_items.reduce((total, item) => total + Number(item.qty) * Number(item.price), 0) - Number(order.discount ?? 0)), 0);
    const paid = (customer.payments ?? []).filter((payment) => payment.status !== "İptal").reduce((sum, payment) => sum + Number(payment.amount), 0);
    const showContact = customer.contact && customer.contact.trim().toLocaleLowerCase("tr-TR") !== customer.name.trim().toLocaleLowerCase("tr-TR");
    return <tr key={customer.id} className={customer.active ? undefined : "product-row-hidden"}><td className="mono">{customer.code}</td><td><b>{customer.name}</b>{!customer.active && <span className="badge st-cancel" style={{ marginLeft: 6 }}>Pasif</span>}{showContact && <div className="sub">{customer.contact}</div>}</td><td className="num">₺{sales.toFixed(2)}</td><td className="num">₺{paid.toFixed(2)}</td><td className={`num ${sales - paid > 0 ? "danger-text" : ""}`}><b>₺{(sales - paid).toFixed(2)}</b></td><td><div className="customer-link-actions"><button className="btn btn-primary btn-sm customer-payment-action" type="button" onClick={() => setPaymentCustomer(customer)}>Tahsilat Al</button><a className="btn btn-sm customer-whatsapp-action" href={`https://wa.me/?text=${encodeURIComponent(`${customer.name} sipariş linkiniz: ${getLink(customer.link_slug)}`)}`} target="_blank" rel="noreferrer"><img src="/whatsapp.svg" alt="" aria-hidden="true" />WhatsApp</a><button className="btn btn-ghost btn-sm" type="button" onClick={() => copyLink(customer.link_slug)}>{copied === customer.link_slug ? "Kopyalandı ✓" : "Linki Kopyala"}</button></div></td><td><div className="customer-link-actions customer-desktop-actions"><button className="btn btn-ghost btn-sm" type="button" onClick={() => setCustomerForm(customer)}>Düzenle</button>{customer.active ? <button className="btn btn-danger btn-sm" type="button" onClick={() => setDeleteCustomerTarget(customer)}>Sil</button> : <form action={reactivateAction} style={{ display: "inline-block" }}><input type="hidden" name="id" value={customer.id} /><button className="btn btn-ghost btn-sm" type="submit">Aktifleştir</button></form>}</div><details className="row-menu customer-mobile-menu"><summary className="icon-btn row-menu-trigger" aria-label={`${customer.name} işlemleri`}><MoreHorizontal size={20} /></summary><div className="row-menu-pop"><button className="row-menu-item" type="button" onClick={() => setCustomerForm(customer)}>Düzenle</button>{customer.active ? <button className="row-menu-item danger" type="button" onClick={() => setDeleteCustomerTarget(customer)}>Sil</button> : <form action={reactivateAction}><input type="hidden" name="id" value={customer.id} /><button className="row-menu-item" type="submit">Aktifleştir</button></form>}</div></details></td></tr>;
  })}</tbody></table></div></div>
  {customerForm !== undefined && <div className="modal-bg open"><div className="modal payment-modal"><div className="modal-head"><div><div className="crumb">Cari hesap</div><h3>{customerForm ? "Cariyi düzenle" : "Yeni cari"}</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => setCustomerForm(undefined)}><X className="ic" /></button></div><CustomerForm customer={customerForm} action={customerForm ? updateAction : createAction} onClose={() => setCustomerForm(undefined)} /></div></div>}
  {paymentCustomer && <div className="modal-bg open payment-entry-backdrop"><div className="modal payment-modal payment-entry-modal"><div className="modal-head"><div><div className="crumb">Cari tahsilat</div><h3>{paymentCustomer.name}</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => { setPaymentCustomer(null); setEditingPaymentId(null); }}><X className="ic" /></button></div><section className="payment-history-section"><div className="payment-section-head"><h4>Tahsilat Geçmişi</h4><span>{paymentCustomer.payments?.length ?? 0} kayıt</span></div>{paymentCustomer.payments?.length ? <div className="payment-history">{paymentCustomer.payments.map((payment) => <div className="payment-history-item" key={payment.id}><div className="payment-history-row"><div className="payment-history-amount"><b>₺{Number(payment.amount).toFixed(2)}</b><span>{payment.method}</span></div><div className="payment-history-meta"><time>{new Date(payment.created_at).toLocaleDateString("tr-TR")}</time>{payment.note && <span>{payment.note}</span>}</div><details className="row-menu payment-row-menu"><summary className="icon-btn row-menu-trigger" aria-label="Tahsilat işlemleri"><MoreHorizontal size={18} /></summary><div className="row-menu-pop"><button className="row-menu-item" type="button" onClick={() => setEditingPaymentId(payment.id)}>Düzenle</button><button className="row-menu-item danger" type="button" onClick={() => setDeletePaymentTarget({ id: payment.id, amount: Number(payment.amount) })}>Sil</button></div></details></div>{editingPaymentId === payment.id && <form className="payment-inline-edit" action={updatePaymentAction}><input type="hidden" name="id" value={payment.id} /><label>Tutar<input className="input" name="amount" type="number" inputMode="decimal" min="0.01" step="0.01" defaultValue={payment.amount} /></label><label>Yöntem<select className="input" name="method" defaultValue={payment.method}><option>Nakit</option><option>Havale</option><option>Kredi Kartı</option></select></label><label className="payment-edit-note">Not<input className="input" name="note" defaultValue={payment.note} placeholder="Not" /></label><div className="payment-inline-actions"><button className="btn btn-ghost btn-sm" type="button" onClick={() => setEditingPaymentId(null)}>Vazgeç</button><button className="btn btn-primary btn-sm" type="submit">Kaydet</button></div></form>}</div>)}</div> : <div className="empty payment-history-empty">Henüz tahsilat kaydı yok.</div>}</section><div className="payment-divider" /><section className="payment-create-section"><h4>Yeni Tahsilat</h4><PaymentForm customer={paymentCustomer} action={paymentAction} onClose={() => setPaymentCustomer(null)} /></section></div></div>}
  {deletePaymentTarget && <div className="modal-bg open"><div className="modal payment-modal"><div className="modal-head"><div><div className="crumb">Tahsilat silme</div><h3>Silme işlemini onayla</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => setDeletePaymentTarget(null)}><X className="ic" /></button></div><DeletePaymentForm payment={deletePaymentTarget} action={deletePaymentAction} onClose={() => { setDeletePaymentTarget(null); setPaymentCustomer(null); }} /></div></div>}
  {deleteCustomerTarget && <div className="modal-bg open"><div className="modal payment-modal"><div className="modal-head"><div><div className="crumb">Cari silme</div><h3>Cariyi sil</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => setDeleteCustomerTarget(null)}><X className="ic" /></button></div><DeleteCustomerForm customer={deleteCustomerTarget} action={deleteCustomerAction} onClose={() => setDeleteCustomerTarget(null)} /></div></div>}</>;
}
