import { getReportsData } from "../../../lib/supabase/queries";

export default async function ReportsPage() {
  const data = await getReportsData();
  return <section><div className="crumb">Yönetim</div><h2 style={{ marginBottom: 16 }}>Raporlar</h2>{data.error && <div className="card card-pad report-error">{data.error}</div>}<div className="stats"><div className="card stat"><div className="k">Bugünkü satış</div><div className="v">₺{data.sales.daily.toFixed(2)}</div><div className="sub">Günlük</div></div><div className="card stat"><div className="k">Bu ay satış</div><div className="v">₺{data.sales.monthly.toFixed(2)}</div><div className="sub">Aylık</div></div><div className="card stat"><div className="k">Toplam tahsilat</div><div className="v">₺{data.payments.toFixed(2)}</div><div className="sub">Payments</div></div><div className="card stat"><div className="k">Tahmini kâr</div><div className="v">₺{data.profit.toFixed(2)}</div><div className="sub">Satış - geliş maliyeti</div></div></div><div className="report-grid"><ReportTable title="Ürün bazlı satış" headers={["Ürün", "Miktar", "Satış", "Maliyet"]} rows={data.products.slice(0, 10).map((row) => [row.name, row.qty, `₺${row.sales.toFixed(2)}`, `₺${row.cost.toFixed(2)}`])} /><ReportTable title="Müşteri bazlı satış" headers={["Müşteri", "Satış"]} rows={data.customers.slice(0, 10).map((row) => [row.name, `₺${row.sales.toFixed(2)}`])} /><div className="report-wide-stack"><ReportTable title="Tedarikçi maliyeti" headers={["Tedarikçi", "Miktar", "Ödenecek"]} rows={data.suppliers.map((row) => [row.name, row.qty, `₺${row.cost.toFixed(2)}`])} /><CriticalStockTable rows={data.critical} /></div></div></section>;
}

function ReportTable({ title, headers, rows }: { title: string; headers: string[]; rows: (string | number)[][] }) { return <div className="card card-pad report-card"><h3>{title}</h3>{rows.length ? <div className="tbl-wrap"><table className="tbl"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${title}-${index}`}>{row.map((value, cell) => <td key={cell} className={cell > 0 ? "num" : ""}>{value}</td>)}</tr>)}</tbody></table></div> : <div className="empty">Kayıt yok.</div>}</div>; }

function CriticalStockTable({ rows }: { rows: { product: string; warehouse: string; quantity: number; critical: number }[] }) {
  const grouped = new Map<string, { warehouse: string; quantity: number; critical: number }[]>();
  rows.forEach((row) => grouped.set(row.product, [...(grouped.get(row.product) ?? []), row]));
  return <div className="card card-pad report-card"><h3>Kritik stok</h3>{grouped.size ? <div className="tbl-wrap"><table className="tbl"><thead><tr><th>Ürün</th><th>Depolar</th><th className="num">En düşük stok</th><th className="num">Eşik</th></tr></thead><tbody>{[...grouped.entries()].map(([product, warehouses]) => <tr key={product}><td><b>{product}</b></td><td><div className="critical-warehouse-list">{warehouses.map((warehouse) => <span className="critical-warehouse-chip" key={`${product}-${warehouse.warehouse}`}>{warehouse.warehouse} <b>{warehouse.quantity}</b></span>)}</div></td><td className="num">{Math.min(...warehouses.map((warehouse) => warehouse.quantity))}</td><td className="num">{Math.max(...warehouses.map((warehouse) => warehouse.critical))}</td></tr>)}</tbody></table></div> : <div className="empty">Kayıt yok.</div>}</div>;
}
