"use client";

import { useMemo, useState } from "react";

type Product = { id: string; name: string; sku: string; category: string; brand: string; unit: string; price: number; image_url?: string };

export default function OrderExperience({ customerName, customerSlug, products }: { customerName: string; customerSlug: string; products: Product[] }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("Tümü"); const [menuOpen, setMenuOpen] = useState(false); const [cart, setCart] = useState<Record<string, number>>({}); const [confirmOpen, setConfirmOpen] = useState(false); const [note, setNote] = useState(""); const [sending, setSending] = useState(false); const [result, setResult] = useState<{ ok: boolean; text: string } | null>(null);
  const categories = ["Tümü", ...new Set(products.map((product) => product.category).filter(Boolean))];
  const filtered = useMemo(() => products.filter((product) => (category === "Tümü" || product.category === category) && (!query || [product.name, product.sku, product.brand].some((value) => value?.toLowerCase().includes(query.toLowerCase())))), [products, query, category]);
  function setQuantity(productId: string, quantity: number) { setCart((current) => ({ ...current, [productId]: Math.max(0, quantity) })); }
  const cartItems = products.filter((product) => (cart[product.id] ?? 0) > 0); const cartUnits = cartItems.reduce((sum, product) => sum + cart[product.id], 0); const cartTotal = cartItems.reduce((sum, product) => sum + cart[product.id] * product.price, 0);
  async function submitOrder() { setSending(true); setResult(null); try { const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ linkSlug: customerSlug, note, items: cartItems.map((product) => ({ productId: product.id, qty: cart[product.id] })) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Sipariş oluşturulamadı."); setConfirmOpen(false); setResult({ ok: true, text: `${payload.orderNo} numaralı siparişiniz alındı.` }); setCart({}); setNote(""); } catch (error) { setResult({ ok: false, text: error instanceof Error ? error.message : "Sipariş oluşturulamadı." }); } finally { setSending(false); } }
  return <>
    <header className="shop-head"><div className="brand"><span className="logo-mark">▣</span> TedarikPro</div><button className="hamburger-btn" type="button" aria-label="Menüyü aç" aria-expanded={menuOpen} onClick={() => setMenuOpen(true)}>☰</button><div className="spacer" /><div className="cust">Sipariş veren firma<b>{customerName}</b></div></header>
    {menuOpen && <><button className="order-drawer-backdrop" aria-label="Menüyü kapat" onClick={() => setMenuOpen(false)} /><aside className="order-drawer" aria-label="Ürün filtreleri"><div className="drawer-head"><h3>Ürünleri Filtrele</h3><button className="icon-btn" aria-label="Kapat" onClick={() => setMenuOpen(false)}>×</button></div><input className="input" aria-label="Ürün ara" placeholder="Ürün adı, SKU veya marka…" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="drawer-label">Kategori</div><div className="cat-chips">{categories.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div><button className="btn btn-primary drawer-apply" onClick={() => setMenuOpen(false)}>Filtreleri Uygula</button></aside></>}
    <main className="shop-wrap"><div className="prod-grid">{filtered.map((product) => { const quantity = cart[product.id] ?? 0; return <article className={`card prod ${quantity ? "in-cart" : ""}`} key={product.id}><img className="product-card-image" src={product.image_url || "/placeholder-product.svg"} alt="" /><div className="cat-tag">{product.category || "Ürün"} · {product.brand}</div><div className="nm">{product.name}</div><div className="meta">SKU: {product.sku}</div><div className="price-row"><span className="price">₺{product.price.toFixed(2)}</span><span className="unit">/ {product.unit}</span></div><div className="qty-ctrl"><button aria-label={`${product.name} azalt`} onClick={() => setQuantity(product.id, quantity - 1)}>−</button><input aria-label={`${product.name} adet`} type="number" min="0" value={quantity} onChange={(event) => setQuantity(product.id, Number(event.target.value) || 0)} /><button aria-label={`${product.name} artır`} onClick={() => setQuantity(product.id, quantity + 1)}>+</button></div></article>; })}</div>{filtered.length === 0 && <div className="empty">Ürün bulunamadı.</div>}<p className="note">{filtered.length} ürün listeleniyor.</p></main>
    {cartUnits > 0 && <div className="cart-bar"><div className="cb-info"><div className="cb-count">{cartItems.length} kalem · {cartUnits} birim</div><div className="cb-total">₺{cartTotal.toFixed(2)}</div></div><button className="btn btn-amber" onClick={() => setConfirmOpen(true)}>Sipariş Ver →</button></div>}
    {confirmOpen && <div className="modal-bg open"><div className="modal order-confirm"><div className="modal-head"><h3>Siparişi onayla</h3><button className="icon-btn" onClick={() => setConfirmOpen(false)}>×</button></div><div className="order-summary">{cartItems.map((product) => <div className="order-summary-row" key={product.id}><span>{product.name} × {cart[product.id]}</span><b>₺{(product.price * cart[product.id]).toFixed(2)}</b></div>)}<div className="order-summary-total"><span>Genel Toplam</span><b>₺{cartTotal.toFixed(2)}</b></div></div><label className="lbl" htmlFor="order-note">Sipariş notu</label><textarea className="input" id="order-note" rows={3} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Teslimat veya sipariş notu…" />{result && !result.ok && <p className="form-error">{result.text}</p>}<button className="btn btn-primary" style={{ width: "100%", marginTop: 14 }} onClick={submitOrder} disabled={sending}>{sending ? "Gönderiliyor…" : "Siparişi Onayla"}</button></div></div>}
    {result?.ok && <div className="modal-bg open"><div className="modal" style={{ textAlign: "center" }}><div style={{ fontSize: 48 }}>✅</div><h3>{result.text}</h3><p className="sub">Siparişiniz yönetim paneline iletildi.</p><button className="btn btn-primary" style={{ marginTop: 16 }} onClick={() => setResult(null)}>Kapat</button></div></div>}
  </>;
}
