"use client";

import { useActionState, useEffect, useRef, useState } from "react";

type Supplier = { id: string; name: string; contact?: string; phone?: string; email?: string; products?: { id: string; name: string; sku: string; cost: number; price: number; active: boolean }[] };
type Action = (formData: FormData) => void | Promise<void>;
type State = { ok: boolean; message: string } | null;

function SupplierForm({ supplier, action, onClose }: { supplier?: Supplier; action: Action; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: State, formData: FormData): Promise<State> => { try { await action(formData); return { ok: true, message: "Kaydedildi." }; } catch (error) { return { ok: false, message: error instanceof Error ? error.message : "İşlem başarısız." }; } }, null);
  useEffect(() => { if (state?.ok) window.setTimeout(onClose, 500); }, [state, onClose]);
  return <form action={formAction} className="supplier-form"><input type="hidden" name="id" value={supplier?.id ?? ""} /><div className="field"><label className="lbl">Tedarikçi adı</label><input className="input" name="name" defaultValue={supplier?.name ?? ""} required /></div><div className="field"><label className="lbl">Yetkili</label><input className="input" name="contact" defaultValue={supplier?.contact ?? ""} /></div><div className="field"><label className="lbl">Telefon</label><input className="input" name="phone" defaultValue={supplier?.phone ?? ""} /></div><div className="field"><label className="lbl">E-posta</label><input className="input" name="email" type="email" defaultValue={supplier?.email ?? ""} /></div>{state && <p className={state.ok ? "form-success" : "form-error"}>{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Kaydediliyor…" : "Kaydet"}</button></div></form>;
}

export default function SupplierManager({ suppliers, createAction, updateAction, deleteAction }: { suppliers: Supplier[]; createAction: Action; updateAction: Action; deleteAction: Action }) {
  const [editing, setEditing] = useState<Supplier | null>(null); const [creating, setCreating] = useState(false); const [selected, setSelected] = useState<Supplier | null>(null); const [search, setSearch] = useState(""); const formRef = useRef<HTMLFormElement>(null);
  const filteredProducts = (selected?.products ?? []).filter((product) => [product.name, product.sku].some((value) => value.toLowerCase().includes(search.toLowerCase())));
  return <><div className="section-head"><div><div className="crumb">Yönetim</div><h2>Tedarikçiler</h2></div><div className="spacer" /><button className="btn btn-primary" type="button" onClick={() => setCreating(true)}>+ Yeni Tedarikçi</button></div><div className="card card-pad"><div className="tbl-wrap"><table className="tbl"><thead><tr><th>Tedarikçi</th><th>Yetkili</th><th>Telefon</th><th>E-posta</th><th>Ürün</th><th></th></tr></thead><tbody>{suppliers.map((supplier) => <tr key={supplier.id}><td><b>{supplier.name}</b></td><td>{supplier.contact || "—"}</td><td>{supplier.phone || "—"}</td><td>{supplier.email || "—"}</td><td><button className="btn btn-ghost btn-sm" type="button" onClick={() => { setSelected(supplier); setSearch(""); }}>{supplier.products?.length ?? 0} ürün</button></td><td><div className="table-actions"><button className="btn btn-ghost btn-sm" type="button" onClick={() => setEditing(supplier)}>Düzenle</button><form ref={formRef} action={deleteAction} onSubmit={(event) => { if (!window.confirm(`${supplier.name} silinsin mi?`)) event.preventDefault(); }}><input type="hidden" name="id" value={supplier.id} /><button className="btn btn-danger btn-sm" type="submit">Sil</button></form></div></td></tr>)}</tbody></table></div>{selected && <div className="supplier-products"><div className="supplier-products-head"><div><div className="crumb">Ürün filtresi</div><h3>{selected.name} ürünleri</h3></div><button className="btn btn-ghost btn-sm" type="button" onClick={() => setSelected(null)}>Kapat</button></div><input className="input" placeholder="Ürün adı veya SKU ara…" value={search} onChange={(event) => setSearch(event.target.value)} />{filteredProducts.length ? <div className="supplier-product-list">{filteredProducts.map((product) => <div className="supplier-product-row" key={product.id}><span><b>{product.name}</b><small>{product.sku}</small></span><span><small>Geliş</small> ₺{Number(product.cost).toFixed(2)} · <small>Satış</small> ₺{Number(product.price).toFixed(2)}</span></div>)}</div> : <div className="empty">Bu filtreye uyan ürün yok.</div>}</div>}</div>{(creating || editing) && <div className="modal-bg open"><div className="modal supplier-modal"><div className="modal-head"><div><div className="crumb">Tedarikçi yönetimi</div><h3>{editing ? "Tedarikçiyi düzenle" : "Yeni tedarikçi"}</h3></div><button className="icon-btn" type="button" onClick={() => { setCreating(false); setEditing(null); }}>×</button></div><SupplierForm supplier={editing ?? undefined} action={editing ? updateAction : createAction} onClose={() => { setCreating(false); setEditing(null); }} /></div></div>}</>;
}
