"use client";

import { useActionState, useEffect, useState } from "react";
import { MoreHorizontal, X } from "lucide-react";
import { ConfirmDialog, type ConfirmConfig } from "@/components";

type SupplierPayment = { id: string; supplier_id: string; amount: number; method: string; note: string; created_at: string };
type Supplier = { id: string; name: string; contact?: string; phone?: string; email?: string; debt?: number; payments?: SupplierPayment[]; products?: { id: string; name: string; sku: string; cost: number; price: number; active: boolean }[] };
type Action = (formData: FormData) => void | Promise<void>;
type State = { ok: boolean; message: string } | null;

function SupplierForm({ supplier, action, onClose }: { supplier?: Supplier; action: Action; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: State, formData: FormData): Promise<State> => { try { await action(formData); return { ok: true, message: "Kaydedildi." }; } catch (error) { return { ok: false, message: error instanceof Error ? error.message : "İşlem başarısız." }; } }, null);
  useEffect(() => { if (state?.ok) window.setTimeout(onClose, 500); }, [state, onClose]);
  return <form action={formAction} className="supplier-form"><input type="hidden" name="id" value={supplier?.id ?? ""} /><div className="field"><label className="lbl">Tedarikçi adı</label><input className="input" name="name" defaultValue={supplier?.name ?? ""} required /></div><div className="field"><label className="lbl">Yetkili</label><input className="input" name="contact" defaultValue={supplier?.contact ?? ""} /></div><div className="field"><label className="lbl">Telefon</label><input className="input" name="phone" defaultValue={supplier?.phone ?? ""} /></div><div className="field"><label className="lbl">E-posta</label><input className="input" name="email" type="email" defaultValue={supplier?.email ?? ""} /></div>{state && <p className={state.ok ? "form-success" : "form-error"}>{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Kaydediliyor…" : "Kaydet"}</button></div></form>;
}

function PaymentForm({ supplier, action, onClose }: { supplier: Supplier; action: Action; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: State, formData: FormData): Promise<State> => {
    try { await action(formData); return { ok: true, message: "Ödeme kaydedildi." }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Ödeme kaydedilemedi." }; }
  }, null);
  useEffect(() => { if (state?.ok) window.setTimeout(onClose, 650); }, [state, onClose]);
  return <form action={formAction} className="payment-modal-form"><input type="hidden" name="supplier_id" value={supplier.id} /><div className="field payment-amount-field"><label className="lbl">Tutar</label><div className="payment-amount-input"><span>₺</span><input className="input" name="amount" type="number" inputMode="decimal" min="0.01" step="0.01" placeholder="0,00" required autoFocus /></div></div><div className="field"><label className="lbl">Yöntem</label><select className="input" name="method"><option>Nakit</option><option>Havale</option><option>Kredi Kartı</option></select></div><details className="payment-note-details"><summary>+ Not ekle</summary><div className="field"><label className="lbl">Not</label><input className="input" name="note" placeholder="Ödeme açıklaması…" /></div></details>{state && <p className={state.ok ? "form-success" : "form-error"}>{state.message}</p>}<div className="modal-actions payment-modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Kaydediliyor…" : "Ödemeyi Kaydet"}</button></div></form>;
}

function DeletePaymentForm({ payment, action, onClose }: { payment: SupplierPayment; action: Action; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(async (_previous: State, formData: FormData): Promise<State> => {
    try { await action(formData); onClose(); return { ok: true, message: "Ödeme silindi." }; }
    catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Ödeme silinemedi." }; }
  }, null);
  return <form action={formAction} className="delete-payment-form"><input type="hidden" name="id" value={payment.id} /><div className="danger-callout"><b>Tehlikeli işlem</b><span>₺{Number(payment.amount).toFixed(2)} tutarındaki ödeme kaydı kalıcı olarak silinecek.</span></div><div className="field"><label className="lbl" htmlFor="delete-supplier-payment-password">Mevcut şifreniz</label><input className="input" id="delete-supplier-payment-password" name="current_password" type="password" autoComplete="current-password" required autoFocus /></div>{state && !state.ok && <p className="form-error">{state.message}</p>}<div className="modal-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Vazgeç</button><button className="btn btn-danger" type="submit" disabled={pending}>{pending ? "Siliniyor…" : "Kalıcı olarak sil"}</button></div></form>;
}

export default function SupplierManager({ suppliers, paymentsReady, createAction, updateAction, deleteAction, paymentAction, updatePaymentAction, deletePaymentAction }: { suppliers: Supplier[]; paymentsReady?: boolean; createAction: Action; updateAction: Action; deleteAction: Action; paymentAction: Action; updatePaymentAction: Action; deletePaymentAction: Action }) {
  const [editing, setEditing] = useState<Supplier | null>(null); const [creating, setCreating] = useState(false); const [selected, setSelected] = useState<Supplier | null>(null); const [search, setSearch] = useState(""); const [confirmConfig, setConfirmConfig] = useState<ConfirmConfig | null>(null);
  const [paymentSupplier, setPaymentSupplier] = useState<Supplier | null>(null);
  const [editingPaymentId, setEditingPaymentId] = useState<string | null>(null);
  const [deletePaymentTarget, setDeletePaymentTarget] = useState<SupplierPayment | null>(null);
  useEffect(() => { if (editingPaymentId) document.querySelectorAll(".payment-row-menu[open]").forEach((menu) => menu.removeAttribute("open")); }, [editingPaymentId]);
  function askDelete(supplier: Supplier) { setConfirmConfig({ title: "Tedarikçiyi sil", message: `“${supplier.name}” silinecek. Bu işlem geri alınamaz.`, confirmLabel: "Sil", danger: true, onConfirm: async () => { const data = new FormData(); data.set("id", supplier.id); await deleteAction(data); } }); }
  const filteredProducts = (selected?.products ?? []).filter((product) => [product.name, product.sku].some((value) => value.toLowerCase().includes(search.toLowerCase())));
  const paid = (supplier: Supplier) => (supplier.payments ?? []).reduce((sum, payment) => sum + Number(payment.amount), 0);
  return <><div className="section-head"><div><div className="crumb">Yönetim</div><h2>Tedarikçiler</h2></div><div className="spacer" /><button className="btn btn-primary" type="button" onClick={() => setCreating(true)}>+ Yeni Tedarikçi</button></div>{paymentsReady === false && <div className="empty" style={{ marginBottom: 12 }}>Tedarikçi ödemeleri için veritabanı hazır değil: Supabase panelinde <b>supabase/patches/019_supplier_payments.sql</b> dosyasını çalıştırın.</div>}<div className="card card-pad supplier-card"><div className="tbl-wrap supplier-table-wrap"><table className="tbl supplier-table"><thead><tr><th>Tedarikçi</th><th className="num">Borç</th><th className="num">Ödenen</th><th className="num">Bakiye</th><th>Ürün</th><th></th></tr></thead><tbody>{suppliers.map((supplier) => {
    const debt = Number(supplier.debt ?? 0); const paidTotal = paid(supplier); const balance = debt - paidTotal;
    const contactLine = [supplier.contact, supplier.phone].filter(Boolean).join(" · ");
    return <tr key={supplier.id}><td className="supplier-name-cell"><b>{supplier.name}</b>{contactLine && <div className="sub">{contactLine}</div>}<dl className="supplier-money-mobile"><div><dt>Borç</dt><dd>₺{debt.toFixed(2)}</dd></div><div><dt>Ödenen</dt><dd>₺{paidTotal.toFixed(2)}</dd></div><div className={balance > 0 ? "danger-text" : ""}><dt>Bakiye</dt><dd><b>₺{balance.toFixed(2)}</b></dd></div></dl></td><td className="num">₺{debt.toFixed(2)}</td><td className="num">₺{paidTotal.toFixed(2)}</td><td className={`num ${balance > 0 ? "danger-text" : ""}`}><b>₺{balance.toFixed(2)}</b></td><td><button className="btn btn-ghost btn-sm" type="button" onClick={() => { setSelected(supplier); setSearch(""); }}>{supplier.products?.length ?? 0} ürün</button></td><td><div className="table-actions"><button className="btn btn-primary btn-sm" type="button" disabled={paymentsReady === false} onClick={() => setPaymentSupplier(supplier)}>Ödeme Yap</button><button className="btn btn-ghost btn-sm" type="button" onClick={() => setEditing(supplier)}>Düzenle</button><button className="btn btn-danger btn-sm" type="button" onClick={() => askDelete(supplier)}>Sil</button></div></td></tr>;
  })}</tbody></table></div>{selected && <div className="supplier-products"><div className="supplier-products-head"><div><div className="crumb">Ürün filtresi</div><h3>{selected.name} ürünleri</h3></div><button className="btn btn-ghost btn-sm" type="button" onClick={() => setSelected(null)}>Kapat</button></div><input className="input" placeholder="Ürün adı veya SKU ara…" value={search} onChange={(event) => setSearch(event.target.value)} />{filteredProducts.length ? <div className="supplier-product-list">{filteredProducts.map((product) => <div className="supplier-product-row" key={product.id}><span><b>{product.name}</b><small>{product.sku}</small></span><span><small>Geliş</small> ₺{Number(product.cost).toFixed(2)} · <small>Satış</small> ₺{Number(product.price).toFixed(2)}</span></div>)}</div> : <div className="empty">Bu filtreye uyan ürün yok.</div>}</div>}</div>{(creating || editing) && <div className="modal-bg open"><div className="modal supplier-modal"><div className="modal-head"><div><div className="crumb">Tedarikçi yönetimi</div><h3>{editing ? "Tedarikçiyi düzenle" : "Yeni tedarikçi"}</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => { setCreating(false); setEditing(null); }}><X className="ic" /></button></div><SupplierForm supplier={editing ?? undefined} action={editing ? updateAction : createAction} onClose={() => { setCreating(false); setEditing(null); }} /></div></div>}
  {paymentSupplier && <div className="modal-bg open payment-entry-backdrop"><div className="modal payment-modal payment-entry-modal"><div className="modal-head"><div><div className="crumb">Tedarikçi ödemesi</div><h3>{paymentSupplier.name}</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => { setPaymentSupplier(null); setEditingPaymentId(null); }}><X className="ic" /></button></div><section className="payment-history-section"><div className="payment-section-head"><h4>Ödeme Geçmişi</h4><span>{paymentSupplier.payments?.length ?? 0} kayıt</span></div>{paymentSupplier.payments?.length ? <div className="payment-history">{paymentSupplier.payments.map((payment) => <div className="payment-history-item" key={payment.id}><div className="payment-history-row"><div className="payment-history-amount"><b>₺{Number(payment.amount).toFixed(2)}</b><span>{payment.method}</span></div><div className="payment-history-meta"><time>{new Date(payment.created_at).toLocaleDateString("tr-TR")}</time>{payment.note && <span>{payment.note}</span>}</div><details className="row-menu payment-row-menu"><summary className="icon-btn row-menu-trigger" aria-label="Ödeme işlemleri"><MoreHorizontal size={18} /></summary><div className="row-menu-pop"><button className="row-menu-item" type="button" onClick={() => setEditingPaymentId(payment.id)}>Düzenle</button><button className="row-menu-item danger" type="button" onClick={() => setDeletePaymentTarget(payment)}>Sil</button></div></details></div>{editingPaymentId === payment.id && <form className="payment-inline-edit" action={updatePaymentAction}><input type="hidden" name="id" value={payment.id} /><label>Tutar<input className="input" name="amount" type="number" inputMode="decimal" min="0.01" step="0.01" defaultValue={payment.amount} /></label><label>Yöntem<select className="input" name="method" defaultValue={payment.method}><option>Nakit</option><option>Havale</option><option>Kredi Kartı</option></select></label><label className="payment-edit-note">Not<input className="input" name="note" defaultValue={payment.note} placeholder="Not" /></label><div className="payment-inline-actions"><button className="btn btn-ghost btn-sm" type="button" onClick={() => setEditingPaymentId(null)}>Vazgeç</button><button className="btn btn-primary btn-sm" type="submit">Kaydet</button></div></form>}</div>)}</div> : <div className="empty payment-history-empty">Henüz ödeme kaydı yok.</div>}</section><div className="payment-divider" /><section className="payment-create-section"><h4>Yeni Ödeme</h4><PaymentForm supplier={paymentSupplier} action={paymentAction} onClose={() => setPaymentSupplier(null)} /></section></div></div>}
  {deletePaymentTarget && <div className="modal-bg open"><div className="modal payment-modal"><div className="modal-head"><div><div className="crumb">Ödeme silme</div><h3>Silme işlemini onayla</h3></div><button className="icon-btn" type="button" aria-label="Kapat" onClick={() => setDeletePaymentTarget(null)}><X className="ic" /></button></div><DeletePaymentForm payment={deletePaymentTarget} action={deletePaymentAction} onClose={() => { setDeletePaymentTarget(null); setPaymentSupplier(null); }} /></div></div>}
  {confirmConfig && <ConfirmDialog config={confirmConfig} onClose={() => setConfirmConfig(null)} />}</>;
}
